### ISSUE TITLE
SVG created by Inkscape won't work

### ISSUE THREAD

**Issue by muuki88** [kartograph/kartograph.js#32]
I wasn't able to create a svg graphic with [Inkscape](http://inkscape.org/) version _0.48.3.1 r9886_.
The xml seems not be parsed correctly, but  I have no clue.

I'm using 
- jquery  1.8.2
- Raphael 2.1.0
- Kartograph.js from master

[Here](https://github.com/lmu-student-web-team/map-of-programming-languages/blob/38e8bd1566604c986538b6b2f5c0f555811c1e7c/public/maps/map.svg) is the file which produced the error (like any other Inkscape svg).

The error occurs in this method

``` javascript
View.fromXML = function(xml) {
    /*
        constructs a view from XML
    */

    var bbox, bbox_xml, h, pad, w;
    w = Number(xml.getAttribute('w')); // Uncaught TypeError: Cannot call method 'getAttribute' of undefined

    h = Number(xml.getAttribute('h'));
    pad = Number(xml.getAttribute('padding'));
    bbox_xml = xml.getElementsByTagName('bbox')[0];
    bbox = BBox.fromXML(bbox_xml);
    return new kartograph.View(bbox, w, h, pad);
  };
```

**Comment by pawelpotoniec** [comment]
@gka 
Please provide some details how to export maps from Illustrator/Inkspace to work well with Kartograph.js?
All files are exported using W3C SVG 1.1 version, but does not contain any metadata required by your lib.
